### ISSUE TITLE
可否添加蜻蜓FM的《张召忠说》？

### ISSUE THREAD

**Issue by Roller44** [forecho/Quicksilver#10]
你好！请问能否添加蜻蜓FM的《张召忠说》？节目编号是 232626。

谢谢！

**Comment by forecho** [comment]
@Roller44 已添加到 [目前已经支持的节目列表](https://github.com/forecho/Quicksilver/wiki/%E7%9B%AE%E5%89%8D%E5%B7%B2%E7%BB%8F%E6%94%AF%E6%8C%81%E7%9A%84%E8%8A%82%E7%9B%AE%E5%88%97%E8%A1%A8)

**Comment by Roller44** [comment]
非常感谢！On Apr 2, 2018 15:12, 蔡正海 <notifications@github.com> wrote:@Roller44 已添加到 目前已经支持的节目列表
