### ISSUE TITLE
节目顺序错乱

### ISSUE THREAD

**Issue by bytemain** [forecho/Quicksilver#13]
总是有很久远的集数时间却是刚刚更新的....

**Comment by forecho** [comment]
@lengthmin 喜马拉雅使用的是更新时间，不是上传时间。这个我再想想办法怎么优化吧。

**Comment by forecho** [comment]
@lengthmin 给个例子吧，我看能不能定位到问题。

**Comment by bytemain** [comment]
https://github.com/DIYgod/RSSHub/blob/master/routes/ximalaya/album.js#L10
https://github.com/DIYgod/RSSHub/blob/master/routes/ximalaya/album.js#L28
我参考了您代码中的api在rsshub这个项目做了一个.
被动式更新
