### ISSUE TITLE
《科技富能量》刚开始正常，之后一直有问题，异常: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by kkzzhizhou** [forecho/Quicksilver#15]
[root@hk rss]# python3 app.py qingting 108012
异常: 'NoneType' object is not subscriptable

**Comment by forecho** [comment]
@kkzzhizhou 应该是你环境问题，我这边环境 OK 了，我顺便帮你加了这个订阅服务，你可以用我的地址。

[科技富能量](http://www.qingting.fm/channels/108012)：http://podcast.forecho.com/qingting/108012.rss
