### ISSUE TITLE
需要新频道

### ISSUE THREAD

**Issue by qiuqianyuanluo** [forecho/Quicksilver#16]
反向流行 https://www.ximalaya.com/renwen/26684396/

您好~需要这个，已微信支持，谢谢啦
感谢建立这个服务！

**Comment by forecho** [comment]
@qiuqianyuanluo 已加上 [反向流行](http://www.ximalaya.com/album/26684396/)：http://podcast.forecho.com/ximalaya/26684396.rss

**Comment by qiuqianyuanluo** [comment]
感谢!

发自我的iPhone

> 在 2019年10月21日，下午6:09，蔡正海 <notifications@github.com> 写道：
> 
> http://podcast.forecho.com/ximalaya/26684396.rss
>
